### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by kozec** [00cpxxx/wine-xinput#2]
Hello,

can I assume that your patch falls under same LGPL license as Wine?

**Comment by 00cpxxx** [comment]
I'm not well versed in license stuff. For me you can do whatever you want with the patch, more likely public domain. Do you think I need to write this somewhere?

**Comment by kozec** [comment]
Yep, adding LICENSE file to root directory would be nice. Without it, it [defaults to almost-nothing-is-allowed copyright](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license)

**Comment by 00cpxxx** [comment]
I have added the file, thanks.

**Comment by kozec** [comment]
Great, thank you.
