### ISSUE TITLE
Doesn't seem to work with Lego Star Wars (xbox one controller)

### ISSUE THREAD

**Issue by wberrier** [00cpxxx/wine-xinput#4]
As mentioned here:

https://bugs.winehq.org/show_bug.cgi?id=38816

[wine_steam_starwars_complete_saga_dinput_xinput_debug_patched.log.zip](https://github.com/00cpxxx/wine-xinput/files/629609/wine_steam_starwars_complete_saga_dinput_xinput_debug_patched.log.zip)

The game detects the controller, but when I go to assign items, the game is waiting for a controller event, but never gets one.

**Comment by 00cpxxx** [comment]
Please get a new +xinput with the following patch if it does not work:
https://github.com/00cpxxx/wine-xinput/blob/master/xinput_quigon.patch

**Comment by 00cpxxx** [comment]
I have updated the patch again with some new stuff. If possible try the newer one.

**Comment by wberrier** [comment]
Here's the testing from the following games:

* Lego Star Wars (doesn't work, same persistent z-axis issue)
* Lego Batman (doesn't work, same persistent z-axis issue)
* Lego Movie (almost works.  First controller appears to work with xinput, but events from the first controller are being registered as the second controller, with all events being z-axis issue.  Doesn't matter if one or two controllers are actually plugged in)
* Lego MARVEL Super Heroes (works! both with one and two controllers)
* Lego Lord of the Ring (works! both with one and two controllers)

Could the not working games be related to issue #3 where the game attempts to use both dinput and xinput?

Attached is the dinput/xinput log from Lego Star Wars (one controller)


[wine_lego_star_wars_dinput_xinput_patched.txt.zip](https://github.com/00cpxxx/wine-xinput/files/664572/wine_lego_star_wars_dinput_xinput_patched.txt.zip)

**Comment by 00cpxxx** [comment]
For the Lego Movie case did you disable the (js) driver in wine control panel?

The Lego Star Wars and Batman is for sure issue #3 according to the log.

Thanks for testing all these games. I believe I can close this and the rest will keep being discussed in issue #3.

**Comment by 00cpxxx** [comment]
I forgot to say in the Lego Movie case it is important to test with a Linux at least 4.3 because of improvements to the xbox driver.

**Comment by wberrier** [comment]
> For the Lego Movie case did you disable the (js) driver in wine control panel?

Yes, the js variant was disabled

> I forgot to say in the Lego Movie case it is important to test with a Linux at least 4.3 because of improvements to the xbox driver.

This was on a 4.8.14 (fedora 24) kernel.

**Comment by 00cpxxx** [comment]
Ok, thanks. Please open a new bug for the Movie game with a +dinput,+xinput attached.

Is the controller wireless?
