### ISSUE TITLE
Doesn't work anymore?

### ISSUE THREAD

**Issue by alexhulbert** [00cpxxx/wine-xinput#6]
I installed this back in February and it worked fine for a couple weeks. Then I didn't touch most of my games for a few months. Now it doesn't work at all! I tried using this patch on the latest version of Wine and that doesn't work either. However, all my controllers _are_ in the control panel.

Currently I'm using koku-wine-xinput, but that only works on about half of my games (whereas historically this patch has worked on all of them)

What can I do to troubleshoot? Could xboxdrv be the issue? How would I go about trying to track down what's wrong with my laptop?

**Comment by 00cpxxx** [comment]
Sorry, currently I'm mostly away from computer life. I tested the patch and it works in Wine 2.14, if you are using wine-staging the patch is known not to work.

**Comment by alexhulbert** [comment]
@00cpxxx Thanks for your comment. It randomly started working yesterday anyway. Enjoy your computer-free life!

**Comment by 00cpxxx** [comment]
Thanks for the quick reply. If possible tell me the controller type you are using and the games so I can add to the working list ;-)
