### ISSUE TITLE
Works fine with "The Witcher 3"

### ISSUE THREAD

**Issue by mfxbe** [00cpxxx/wine-xinput#7]
I played Witcher 3 with this patch for a couple of hours everything seems to work fine (apart from my system not reconsigning any actions and tourning off the screen)

I guess you cloud add it to the list of games that were tested and work.

**Comment by 00cpxxx** [comment]
Thanks for the report ;-)

The screen off problem is a known issue:
https://bugs.winehq.org/show_bug.cgi?id=13616
